### GENERAL ###
server:
  port: 8080
  servlet.context-path: /api/clientes

spring:
  application.name: cliente
#  cloud.config.fail-fast: true
#  main.web-application-type: servlet
#  jackson:
#    serialization.WRITE_DATES_AS_TIMESTAMPS: false
#    deserialization.fail-on-unknown-properties: false
#    default-property-inclusion: NON_ABSENT
#    profiles.default: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cliente
    password: root
    username: root
  jpa:
    show-sql: true

logging:
  level:
    root: ERROR
    io.platformbuilders: INFO
    org.springframework: ERROR
    javax.management: ERROR