### GENERAL ###
server:
  port: 8080
  servlet.context-path: /api

spring:
  application.name: cliente
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cliente
    password: root
    username: root
  jpa:
    show-sql: true
  liquibase:
    enabled: true

logging:
  level:
    root: ERROR
    io.platformbuilders: INFO
    org.springframework: ERROR
    javax.management: ERROR
    org.springframework.web: TRACE