# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: cliente
      MYSQL_PASSWORD: dQ6Nb&P3OUwT
      MYSQL_DATABASE: cliente
    expose:
      - "3306"
    volumes:
      - mysqldb:/var/lib/mysql

volumes:
  mysqldb:
