# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: cliente
      MYSQL_PASSWORD: dQ6Nb&P3OUwT
      MYSQL_DATABASE: cliente
    volumes:
      - mysqldb:/var/lib/mysql

  cliente-app:
    container_name: client-app
    image: guilhermecesar/builders-cliente
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysqldb:
